services:
  db:
    image: postgres:16
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${DATABASE__USERNAME}
      POSTGRES_PASSWORD: ${DATABASE__PASSWORD}
      POSTGRES_DB: ${DATABASE__NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ..
      dockerfile: projects/api/Containerfile
    env_file:
      - ../.env
    environment:
      # if your code uses DATABASE_URL too, keep it:
      DATABASE_URL: postgresql://${DATABASE__USERNAME}:${DATABASE__PASSWORD}@${DATABASE__HOST}:${DATABASE__PORT}/${DATABASE__NAME}
    depends_on:
      - db
    ports:
      - "8000:8000"

  outlier_detection:
    build:
      context: ..
      dockerfile: projects/outlier_detection_api/Containerfile
    env_file:
      - ../.env
    environment:
      # if your code uses DATABASE_URL too, keep it:
      DATABASE_URL: postgresql://${DATABASE__USERNAME}:${DATABASE__PASSWORD}@${DATABASE__HOST}:${DATABASE__PORT}/${DATABASE__NAME}
    depends_on:
      - db
    ports:
      - "8001:8000"

  forecasting:
    build:
      context: ..
      dockerfile: projects/forecasting/Containerfile
    env_file:
      - ../.env
    environment:
      DATABASE_URL: postgresql://${DATABASE__USERNAME}:${DATABASE__PASSWORD}@${DATABASE__HOST}:${DATABASE__PORT}/${DATABASE__NAME}
    depends_on:
      - db
    ports:
      - "8002:8000"

volumes:
  pgdata:
