services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: timeseriesdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  outlier_detection:
    build:
      context: .
      dockerfile: projects/outlier_detection/Containerfile
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/timeseriesdb
    depends_on:
      - db
    ports:
      - "8001:8000"

  forecasting:
    build:
      context: .
      dockerfile: projects/forecasting/Containerfile
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/timeseriesdb
    depends_on:
      - db
    ports:
      - "8002:8000"

volumes:
  pgdata:
