services:
  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  outlier_detection:
    build:
      context: .
      dockerfile: projects/outlier_detection/Containerfile
    env_file:
      - .env
    environment:
      # if your code uses DATABASE_URL too, keep it:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    depends_on:
      - db
    ports:
      - "8001:8000"

  forecasting:
    build:
      context: .
      dockerfile: projects/forecasting/Containerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  pgdata:
